### ISSUE TITLE
Return single pdf after batch label creation

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#77] opened 2017-05-15 09:43 UTC
When creating multiple shipping labels the user should afterwards not have to visit each order again to download the label that was created. The best solution would be to generate a single pdf with all labels that were created during the batch label request.

We've got great feedback from people who are using the shopware plugin where this has already been implemented. 

If you're interested, here's the login data:
* URL: http://shopware.site-concept.de/demoshop/backend/
* User: **demo1**
* Password: **demo**

My suggestion (without knowing the ins & outs of Wordpress/WooCommerce would be to create a single pdf file with the labels that where created and save it the place where WP/WC is normally saving its generated files like images. After the pdf has been created you could send a download directive to the browser so the customer won't have to click on a link to download the file.

I'm not sure if the combined pdf should be deleted afterwards or if the user should be able to delete it from the file system.

**Comment by mahype** [comment] 2017-06-07 12:07
The label creation works fine! Also I like the notice above the Order overview page.

but I have some points:

1.  I get the following error message on every page of the WP-Admin:

Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/shipcloud-for-woocommerce/woocommerce-shipcloud.php on line 365

2. The function "attach_downloads()" should belong to the bulk class.

3. The created PDF file should not be created in the plugin directory, it should be created in the download directory of WordPress. Because if secure configured, this directory should not be writable and this will lead to errors at customer installs.

**Comment by mahype** [comment] 2017-06-07 12:10
Oh, I forgot something:

4. The buttons should have space between each other.

**Comment by sourcerer-mike** [comment] 2017-06-07 21:32
on 1) I almost said "can't reproduce" then it came to my mind that you are still in an existing session (I guess) and this session would get the new capability after loggin in again. Damn. Solved it.

**Comment by sourcerer-mike** [comment] 2017-06-07 21:45
on 2) I moved it. Was in the general class because it felt so close to notices (with "start download after redirects") and the session handling was there too.

**Comment by sourcerer-mike** [comment] 2017-06-07 21:50
on 3) Needs special verification by @mahype . The current storage path is "wp-content/woocommerce-shipcloud/".

Neither within the plugin, nor in the uploads dir to prevent importer fetching this and displaying it on the media page. Which path would you like instead?

**Comment by sourcerer-mike** [comment] 2017-06-07 22:13
on 4) Space added.

**Comment by andrecedik** [comment] 2017-06-08 05:17
Ok, I was able to test this now. Two things that I have to add:

1.) When selecting multiple orders and clicking on "Create labels" I still only get a message that those labels where created. I have to enter this context again and click on "Create PDF" to get the pdf. I'd be awesome if you can get the single PDF with those labels right after creating them.

2.) When clicking on "Create PDF" it's mandatory to have package dimensions selected. I know we need this to be able to create a shipment in case we haven't created one before, but I receive a http 500 error when not selecting dimensions. I think we should give an error message in this case. Since I've created shipping labels for my orders before, shouldn't a get a pdf even without supplying this data?

Question: What is the intent of the user when clicking "Create PDF"? 
- If this means "create PDF from already existing shipping labels" than the user shouldn't have to enter package dimensions and select a carrier. 
- If the users wants to create a shipping label for shipments without labels, than we need the data.
- It is also possible that the users always wants to create a new shipping label and get a pdf with all labels. So it doesn't matter if there already is one. This is the use case I would expect when clicking on "Create labels".

**Comment by sourcerer-mike** [comment] 2017-06-08 07:21
I will solve the 1. by merging the two buttons which also solves the second.
Last week we were unclear if we want two buttons (so the user decides, if he wants the PDF)
or just one button which spills out the PDF all the time (naggy-mode).
Reading your input it will be the single-button solution.

The intent of the PDF button was for development mostly and usability.

**Comment by mahype** [comment] 2017-06-09 10:46
Hi @sourcerer-mike,

I just merged your branch to release/1.3.0, but after merging everything, I cannot create labels anymore. Can you please check this in the branch release/1.3.0.

Greetings,

Sven

**Comment by mahype** [comment] 2017-06-09 10:54
I also have changed the path to the upload directory, but I could not check this, because of the described problem. Can you check this too? Thank you!

**Comment by sourcerer-mike** [comment] 2017-06-10 11:59
I've solved this it seems. 
As the merge brought some old code in and things seem different on the API too I like to continue non-pdf related things here: https://github.com/awsmug/shipcloud-for-woocommerce/issues/96

Because of what I've seen it feels that there are still some flaws hidden.

**Comment by mahype** [comment] 2017-06-12 12:11
Perfect! 

But now I have two error messages:

> Warning: array_merge(): Argument #2 is not an array in /var/www/html/wp-content/plugins/shipcloud-for-woocommerce/woocommerce-shipcloud.php on line 273

> Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/shipcloud-for-woocommerce/woocommerce-shipcloud.php on line 366

Can you check that?

**Comment by sourcerer-mike** [comment] 2017-06-14 12:13
Best thing is: Near message 1 are things made to prevent message 2 :D 
(fixed in release/1.3.0 branch)

**Closed** 2017-06-20 09:36 UTC
Labels: enhancement, high priority
